defaults: &defaults
  encoding: unicode

development_defaults: &development_defaults
  <<: *defaults
  adapter: sqlite3

development:
  <<: *development_defaults
  database: db/development.sqlite3

test:
  <<: *development_defaults
  database: db/test.sqlite3

production:
  <<: *defaults
  adapter: postgresql
